Make WeightedTags updater optional in LinksRecommendationUpdater
When running GrowthExperiments tests without CirrusSearch loaded, the
GrowthExperimentsLinkRecommendationUpdater fails to initialize:

  9) GrowthExperiments\Tests\Integration\ServiceWiringTest::testService
     with data set "GrowthExperimentsLinkRecommendationUpdater"
     ('GrowthExperimentsLinkRecommen...pdater')
  Error: Class "CirrusSearch\CirrusSearchServices" not found

By making CirruSearch optional, on CI I will be able have a job that
runs solely with extensions strictly required in `extension.json`.

Disable the weighted tags updater when CirrusSearch is not available.
I have used the same pattern used for the service
GrowthExperimentsLinkRecommendationHelper.

Bug: T415278
Change-Id: Ib55f710e5f3efb0ba66a3e46f7c8a3bb466636e8