phpunit: Set GEHelpPanelHelpDeskTitle manually
In local setup, when using on-wiki config, the testValidateRelevantTitle
test fails with:

 1) GrowthExperiments\Tests\HelpdeskQuestionPosterTest::testValidateRelevantTitle
 Error: Call to a member function isRedirect() on null

This is because `$wikiConfig->get( 'GEHelpPanelHelpDeskTitle'
)` in HelpPanel::getHelpDeskTitle() returns null. Manually set the
global so the test can succeed regardless of what is in wikiConfig.

Change-Id: I99ce8b397fb1e8e3cfb5f6fc46078ebbe7812317