tests: Disable main cache in several test suites
Core currently runs by default with a fairly odd hybrid where some
caches are set to HashBagOStuff and reset between each test case (
e.g. MessageCache, l10n, Main cache, etc), some caches are
persistent, and some caches are disabled. In particular the "main"
cache was enabled (as a per-test 'hash'), but the more common wrapper
interface (WANObjectCache) was disabled instead of wrapping the "main"
cache as it normally would.

I'm fixing this in I53781a8c06ebb2583f6ca8 in core, but noticed
several test failures that may be worth looking into. It means the
called source code (or hopefully, just the test) may be forgetting
to issue a cache purge, or missing a dependency injection, or
unintentionally retaining state between tests, or incompletely
bypassing the cache for logic where a cache miss is needed.

Summary of the 8 failures, with a subset of debug messages that
may be of use:

1. GrowthExperiments\Tests\SpecialEnrollAsMentorTest::testIsMentor
   Failed asserting that false is true.
   …/GrowthExperiments/…/SpecialEnrollAsMentorTest.php:62
   ==Logs==
   [objectcache] [debug] fetchOrRegenerate(wikidb-unittest_:GrowthExperiments:config:8:GrowthMentors.json): volatile hit []

2. GrowthExperiments\Tests\SpecialManageMentorsTest::testNotAuthorizedRemoveMentor
   Failed asserting that false is true.
   /…/GrowthExperiments/…/SpecialManageMentorsTest.php:132
   ==Logs==
   [objectcache] [debug] fetchOrRegenerate(wikidb-unittest_:GrowthExperiments:config:8:GrowthMentors.json): volatile hit []

3. GrowthExperiments\Tests\SpecialManageMentorsTest::testAuthorizedRemoveMentor
   Failed asserting that false is true.
   /…/GrowthExperiments/…/SpecialManageMentorsTest.php:153
   ==Logs=
   [objectcache] [debug] getWithSetCallback(wikidb-unittest_:page-content-model:9): process cache hit []
   [objectcache] [debug] getWithSetCallback(global:SqlBlobStore-blob:wikidb-unittest_:tt%3A8): process cache hit []
   [objectcache] [debug] fetchOrRegenerate(wikidb-unittest_:GrowthExperiments:config:8:GrowthMentors.json): volatile hit []

4. GrowthExperiments\Tests\SpecialManageMentorsTest::testAuthorizedEditMentor
   Failed asserting that 'this is intro' contains "new intro".
   /…/GrowthExperiments/…/SpecialManageMentorsTest.php:224
   ==Logs==
   [objectcache] [debug] getWithSetCallback(wikidb-unittest_:page-content-model:10): process cache hit []
   [objectcache] [debug] getWithSetCallback(global:SqlBlobStore-blob:wikidb-unittest_:tt%3A9): process cache hit []
   [objectcache] [debug] fetchOrRegenerate(wikidb-unittest_:GrowthExperiments:config:8:GrowthMentors.json): volatile hit []
   [objectcache] [debug] getWithSetCallback(global:SqlBlobStore-blob:wikidb-unittest_:tt%3A10): process cache hit []
   [objectcache] [debug] fetchOrRegenerate(wikidb-unittest_:GrowthExperiments:config:8:GrowthMentors.json): volatile hit []

5. GrowthExperiments\Tests\SpecialMentorDashboardTest::testIsMentor
6. GrowthExperiments\Tests\SpecialQuitMentorshipTest::testGet with data set "has mentees" (true)
7. GrowthExperiments\Tests\SpecialQuitMentorshipTest::testPost with data set "has mentees" (true)
8. GrowthExperiments\Tests\SpecialQuitMentorshipTest::testPost with data set "no mentees" (false)

And 3 PHP errors:

1. GrowthExperiments\Tests\ApiQueryMentorStatusTest::testDefaultExecute
   ApiUsageException: Permission denied.
2. GrowthExperiments\Tests\ApiQueryMentorStatusTest::testAway
   ApiUsageException: Permission denied.
3. GrowthExperiments\Tests\MentorPageMentorManagerTest::testGetMentorUserNew
   GrowthExperiments\WikiConfigException: Mentorship: No mentor available

Failure details in this CI output (build is preserved):
<https://integration.wikimedia.org/ci/job/wmf-quibble-core-vendor-mysql-php74-docker/11181/>

Change-Id: If890622eed0d0f8b4bd73d36ba1815a3d760ea05